### ISSUE TITLE
Providing an invalid city does not handle error gracefully 

### ISSUE THREAD

**Issue by sangv** [smuntean/now-you-snow#13]
![image](https://user-images.githubusercontent.com/1299079/46972466-92b2f280-d08c-11e8-8780-39599a0156c7.png)

Leads to this:

![image](https://user-images.githubusercontent.com/1299079/46972488-9f374b00-d08c-11e8-8f09-1af4cea85d92.png)

**Comment by sarathrasher** [comment]
I revised my if statement and am now unable to replicate this error. I fixed this and another bug I encountered when solving this bug and those have both been merged with master.
